#!/bin/sh

# Example names. $JOBNAME only affects the names of the terminal STDOUT log
# files generated by each CASA process.
JOBNAME="pipe_log"
SCRIPTNAME=run_pipe.py

# The number of CASA instances or jobs/batches should be about half the number
# of CPUs requested (i.e., ~two CPUs per job). The shell environment variable
# will be retrieved in the script. Note that there must be more chunks than
# batches (or an equal number, with the minimum of one chunk per CASA job).
NBATCHES=8


# Start up the number of jobs asynchronously by appending "&"
for ((i=0; i<$NBATCHES; i++))
do
    casa --nogui --nologger -c "execfile('$SCRIPTNAME'); _run_subset($i)" >& casa_imaging_${JOBNAME}_${i}.out &
done
wait


